### ISSUE TITLE
Can't get a map 

### ISSUE THREAD

**Issue by stefanosPap** [prithvisekhar/ROS-AD-SLAM-Evaluation#3]
Hello! I am trying to run gmapping with CARLA following the instructions given in README.md but the map doesn't exist in RViz. Specifically, I am running the following commands: 
* cd /opt/carla-simulator/bin
* ./CarlaUE4.sh
* roslaunch carla_ros_bridge carla_ros_bridge_with_example_ego_vehicle.launch 
* roslaunch carlabg Gmapping_Carla.launch 
I am trying to see if the corresponding topics take messages correctly using the command "rostopic hz 'topic name' or rostopic echo 'topic name' " but I take the following result which means that these topics don't take any messages.
![Screenshot from 2020-08-27 17-32-53](https://user-images.githubusercontent.com/36679249/91456905-78ebb480-e88c-11ea-8870-c65dec49d250.png)
I know that gmapping needs as input "sensor_msgs/LaserScan" messages in order to work properly, but as I see at the available topics the output of the Lidar gives "sensor_msgs/PointCloud2" messages. Then I tried to convert them from pointcloud2 to laserscan by using this package http://wiki.ros.org/pointcloud_to_laserscan and running the following command: 
* rosrun pointcloud_to_laserscan pointcloud_to_laserscan_node cloud_in:= 'topic name of point cloud' but I couldn't take the map. 

Generally, I couldn't make any algorithm to work properly and give me back a map, so your help will be precious. I can give you information about other ways that I tried to run SLAM with CARLA and ROS. Thanks!

I am using: 
* Ubuntu 16.04
* ROS kinetic
* CARLA 0.9.7 installed by apt-get
* carla_ros_bridge installed by apt-get

**Comment by kankan-sarkar** [comment]
Hi  Stefanos,

Sorry to hear that you are facing issues to get the slam running.
I assume you are not using the custom source that we have built to support
the slam algorithms. Can you please confirm if you have compiled the below
directory?

https://github.com/prithvisekhar/ROS-AD-SLAM-Evaluation/tree/master/catkin_bak


If not, then try the following steps to replicate our test.

1. Install the ROS bridge (which you have already done).
2. Create a ROS catkin workspace (workspace tutorial LINK
<http://wiki.ros.org/catkin/Tutorials/create_a_workspace>) and copy the src
folder from
https://github.com/prithvisekhar/ROS-AD-SLAM-Evaluation/tree/master/catkin_bak
to the new workspace.
3. Then build the workspace and follow the rest of the tutorial to run the
slam.

Regards,
Kankan

**Comment by stefanosPap** [comment]
Hi Kankan! 

Sorry, I didn't mention that before but I've already built the catkin_workspace successfully, so I think that it's not a problem. When I run "roslaunch carla_ros_bridge carla_ros_bridge_with_example_ego_vehicle.launch" I take this error "timeout while waiting for world info". However, the vehicle is created successfully but I can't control it by using the keyboard so I think that it doesn't work properly. I have some questions and it will be very useful if you can answer them. 1) Do you think that it doesn't need a pointcloud to laserscan conversion in order to run gmapping properly? 2) Should I change something on topics or frames of the launch file of gmapping? 3) Is there another way to take a map such as running  "roslaunch carla_ros_bridge carla_ros_bridge_with_rviz.launch" and a script with a simple vehicle with a lidar attached to it (I' ve already created a script like this, so if you want it, I can upload the code)? 

Thank you very much for your time!
Stefanos

**Comment by kankan-sarkar** [comment]
Hi Stefanos, Can you test the repo in Ubuntu 18.04 with ROS melodic ? I
will try to check for ubuntu 16.04

Regards,
Kankan

**Comment by stefanosPap** [comment]
Hi Kankan, it's a bit difficult for me, because I cannot format my current laptop right now. Although thanks for your help. Let me know if you have any update.   

Regards,
Stefanos
