### ISSUE TITLE
Missing CarlaPCtoLS.launch in pointcloud_to_laserscan

### ISSUE THREAD

**Issue by YWangXJ** [prithvisekhar/ROS-AD-SLAM-Evaluation#4]
It seems that the `CarlaPCtoLS.launch` file in `pointcloud_to_laserscan` is missing in this repo. Could you please kindly update it in this repo or just copy and paste it here. I'm figuring out how to publish 2D LaserScan in Carla.

Great repo! Thanks in advance!

**Comment by kankan-sarkar** [comment]
Please download the ROS package to convert CARLA point cloud to laser scan package from [here](https://github.com/trripy/PointcloudTo2DLaser.git) , this is a modified version of the original implementation which can be found [here](http://wiki.ros.org/pointcloud_to_laserscan)

Hope This Helps 
Cheers!
